version: '3.8'

services:
  markov-feed:
    image: iamtakagi/markov-feed
    restart: unless-stopped
    build:
      args:
        TZ: Asia/Tokyo
        USERS: iam_takagi
        TWITTER_CK: xxx
        TWITTER_CS: xxx
        TWITTER_AT: xxx
        TWITTER_ATS: xxx
        DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/xxx/xxx
